[package]
name = "prisma-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust.git", rev = "57d154b5d897510905ab8a605d4fae79f5372b56", features = [
  "rspc",
  "sqlite-create-many",
] }
